//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Models", "FK_CategoryMappings_Categories", "Categories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CashBack.Data.Category), "CategoryMappings", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CashBack.Data.CategoryMapping))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Models", "FK_ProductCategories_Categories", "Categories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CashBack.Data.Category), "ProductCategories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CashBack.Data.ProductCategory))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Models", "FK_ProductCategories_Products", "Products", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CashBack.Data.Product), "ProductCategories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CashBack.Data.ProductCategory))]

// Original file name:
// Generation date: 6/19/2009 11:55:45 PM
namespace CashBack.Data
{
    
    /// <summary>
    /// There are no comments for CashBackDBEntities in the schema.
    /// </summary>
    public partial class CashBackDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CashBackDBEntities object using the connection string found in the 'CashBackDBEntities' section of the application configuration file.
        /// </summary>
        public CashBackDBEntities() : 
                base("name=CashBackDBEntities", "CashBackDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CashBackDBEntities object.
        /// </summary>
        public CashBackDBEntities(string connectionString) : 
                base(connectionString, "CashBackDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CashBackDBEntities object.
        /// </summary>
        public CashBackDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CashBackDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for BrandSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Brand> BrandSet
        {
            get
            {
                if ((this._BrandSet == null))
                {
                    this._BrandSet = base.CreateQuery<Brand>("[BrandSet]");
                }
                return this._BrandSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Brand> _BrandSet;
        /// <summary>
        /// There are no comments for CategorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Category> CategorySet
        {
            get
            {
                if ((this._CategorySet == null))
                {
                    this._CategorySet = base.CreateQuery<Category>("[CategorySet]");
                }
                return this._CategorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Category> _CategorySet;
        /// <summary>
        /// There are no comments for CategoryMappingSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CategoryMapping> CategoryMappingSet
        {
            get
            {
                if ((this._CategoryMappingSet == null))
                {
                    this._CategoryMappingSet = base.CreateQuery<CategoryMapping>("[CategoryMappingSet]");
                }
                return this._CategoryMappingSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CategoryMapping> _CategoryMappingSet;
        /// <summary>
        /// There are no comments for ProductCategorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProductCategory> ProductCategorySet
        {
            get
            {
                if ((this._ProductCategorySet == null))
                {
                    this._ProductCategorySet = base.CreateQuery<ProductCategory>("[ProductCategorySet]");
                }
                return this._ProductCategorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProductCategory> _ProductCategorySet;
        /// <summary>
        /// There are no comments for ProductSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Product> ProductSet
        {
            get
            {
                if ((this._ProductSet == null))
                {
                    this._ProductSet = base.CreateQuery<Product>("[ProductSet]");
                }
                return this._ProductSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Product> _ProductSet;
        /// <summary>
        /// There are no comments for StoreSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Store> StoreSet
        {
            get
            {
                if ((this._StoreSet == null))
                {
                    this._StoreSet = base.CreateQuery<Store>("[StoreSet]");
                }
                return this._StoreSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Store> _StoreSet;
        /// <summary>
        /// There are no comments for BrandSet in the schema.
        /// </summary>
        public void AddToBrandSet(Brand brand)
        {
            base.AddObject("BrandSet", brand);
        }
        /// <summary>
        /// There are no comments for CategorySet in the schema.
        /// </summary>
        public void AddToCategorySet(Category category)
        {
            base.AddObject("CategorySet", category);
        }
        /// <summary>
        /// There are no comments for CategoryMappingSet in the schema.
        /// </summary>
        public void AddToCategoryMappingSet(CategoryMapping categoryMapping)
        {
            base.AddObject("CategoryMappingSet", categoryMapping);
        }
        /// <summary>
        /// There are no comments for ProductCategorySet in the schema.
        /// </summary>
        public void AddToProductCategorySet(ProductCategory productCategory)
        {
            base.AddObject("ProductCategorySet", productCategory);
        }
        /// <summary>
        /// There are no comments for ProductSet in the schema.
        /// </summary>
        public void AddToProductSet(Product product)
        {
            base.AddObject("ProductSet", product);
        }
        /// <summary>
        /// There are no comments for StoreSet in the schema.
        /// </summary>
        public void AddToStoreSet(Store store)
        {
            base.AddObject("StoreSet", store);
        }
    }
    /// <summary>
    /// There are no comments for Models.Brand in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Models", Name="Brand")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Brand : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Brand object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="brandID">Initial value of BrandID.</param>
        /// <param name="brandName">Initial value of BrandName.</param>
        /// <param name="program">Initial value of Program.</param>
        /// <param name="status">Initial value of Status.</param>
        public static Brand CreateBrand(int id, string brandID, string brandName, string program, int status)
        {
            Brand brand = new Brand();
            brand.ID = id;
            brand.BrandID = brandID;
            brand.BrandName = brandName;
            brand.Program = program;
            brand.Status = status;
            return brand;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property BrandID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandID
        {
            get
            {
                return this._BrandID;
            }
            set
            {
                this.OnBrandIDChanging(value);
                this.ReportPropertyChanging("BrandID");
                this._BrandID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("BrandID");
                this.OnBrandIDChanged();
            }
        }
        private string _BrandID;
        partial void OnBrandIDChanging(string value);
        partial void OnBrandIDChanged();
        /// <summary>
        /// There are no comments for Property BrandName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName
        {
            get
            {
                return this._BrandName;
            }
            set
            {
                this.OnBrandNameChanging(value);
                this.ReportPropertyChanging("BrandName");
                this._BrandName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("BrandName");
                this.OnBrandNameChanged();
            }
        }
        private string _BrandName;
        partial void OnBrandNameChanging(string value);
        partial void OnBrandNameChanged();
        /// <summary>
        /// There are no comments for Property BrandURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandURL
        {
            get
            {
                return this._BrandURL;
            }
            set
            {
                this.OnBrandURLChanging(value);
                this.ReportPropertyChanging("BrandURL");
                this._BrandURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BrandURL");
                this.OnBrandURLChanged();
            }
        }
        private string _BrandURL;
        partial void OnBrandURLChanging(string value);
        partial void OnBrandURLChanged();
        /// <summary>
        /// There are no comments for Property ImageURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL
        {
            get
            {
                return this._ImageURL;
            }
            set
            {
                this.OnImageURLChanging(value);
                this.ReportPropertyChanging("ImageURL");
                this._ImageURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ImageURL");
                this.OnImageURLChanged();
            }
        }
        private string _ImageURL;
        partial void OnImageURLChanging(string value);
        partial void OnImageURLChanged();
        /// <summary>
        /// There are no comments for Property Program in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Program
        {
            get
            {
                return this._Program;
            }
            set
            {
                this.OnProgramChanging(value);
                this.ReportPropertyChanging("Program");
                this._Program = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Program");
                this.OnProgramChanged();
            }
        }
        private string _Program;
        partial void OnProgramChanging(string value);
        partial void OnProgramChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
    }
    /// <summary>
    /// There are no comments for Models.Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Models", Name="Category")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Category : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        /// <param name="categoryName">Initial value of CategoryName.</param>
        /// <param name="status">Initial value of Status.</param>
        public static Category CreateCategory(int categoryID, string categoryName, int status)
        {
            Category category = new Category();
            category.CategoryID = categoryID;
            category.CategoryName = categoryName;
            category.Status = status;
            return category;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this.ReportPropertyChanging("CategoryID");
                this._CategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryID");
                this.OnCategoryIDChanged();
            }
        }
        private int _CategoryID;
        partial void OnCategoryIDChanging(int value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property CategoryName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this._CategoryName;
            }
            set
            {
                this.OnCategoryNameChanging(value);
                this.ReportPropertyChanging("CategoryName");
                this._CategoryName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CategoryName");
                this.OnCategoryNameChanged();
            }
        }
        private string _CategoryName;
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        /// <summary>
        /// There are no comments for Property ParentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentID
        {
            get
            {
                return this._ParentID;
            }
            set
            {
                this.OnParentIDChanging(value);
                this.ReportPropertyChanging("ParentID");
                this._ParentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentID");
                this.OnParentIDChanged();
            }
        }
        private global::System.Nullable<int> _ParentID;
        partial void OnParentIDChanging(global::System.Nullable<int> value);
        partial void OnParentIDChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for CategoryMappings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Models", "FK_CategoryMappings_Categories", "CategoryMappings")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CategoryMapping> CategoryMappings
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CategoryMapping>("Models.FK_CategoryMappings_Categories", "CategoryMappings");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CategoryMapping>("Models.FK_CategoryMappings_Categories", "CategoryMappings", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProductCategories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Models", "FK_ProductCategories_Categories", "ProductCategories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProductCategory> ProductCategories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProductCategory>("Models.FK_ProductCategories_Categories", "ProductCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProductCategory>("Models.FK_ProductCategories_Categories", "ProductCategories", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Models.CategoryMapping in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// ReferenceCategoryID
    /// Program
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Models", Name="CategoryMapping")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CategoryMapping : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CategoryMapping object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        /// <param name="referenceCategoryID">Initial value of ReferenceCategoryID.</param>
        /// <param name="program">Initial value of Program.</param>
        public static CategoryMapping CreateCategoryMapping(int categoryID, int referenceCategoryID, string program)
        {
            CategoryMapping categoryMapping = new CategoryMapping();
            categoryMapping.CategoryID = categoryID;
            categoryMapping.ReferenceCategoryID = referenceCategoryID;
            categoryMapping.Program = program;
            return categoryMapping;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this.ReportPropertyChanging("CategoryID");
                this._CategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryID");
                this.OnCategoryIDChanged();
            }
        }
        private int _CategoryID;
        partial void OnCategoryIDChanging(int value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ReferenceCategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferenceCategoryID
        {
            get
            {
                return this._ReferenceCategoryID;
            }
            set
            {
                this.OnReferenceCategoryIDChanging(value);
                this.ReportPropertyChanging("ReferenceCategoryID");
                this._ReferenceCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReferenceCategoryID");
                this.OnReferenceCategoryIDChanged();
            }
        }
        private int _ReferenceCategoryID;
        partial void OnReferenceCategoryIDChanging(int value);
        partial void OnReferenceCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property Program in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Program
        {
            get
            {
                return this._Program;
            }
            set
            {
                this.OnProgramChanging(value);
                this.ReportPropertyChanging("Program");
                this._Program = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Program");
                this.OnProgramChanged();
            }
        }
        private string _Program;
        partial void OnProgramChanging(string value);
        partial void OnProgramChanged();
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Models", "FK_CategoryMappings_Categories", "Categories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Category Categories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("Models.FK_CategoryMappings_Categories", "Categories").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("Models.FK_CategoryMappings_Categories", "Categories").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Category> CategoriesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("Models.FK_CategoryMappings_Categories", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Category>("Models.FK_CategoryMappings_Categories", "Categories", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Models.ProductCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// ProductID
    /// Type
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Models", Name="ProductCategory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProductCategory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ProductCategory object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="type">Initial value of Type.</param>
        public static ProductCategory CreateProductCategory(int categoryID, int productID, int type)
        {
            ProductCategory productCategory = new ProductCategory();
            productCategory.CategoryID = categoryID;
            productCategory.ProductID = productID;
            productCategory.Type = type;
            return productCategory;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this.ReportPropertyChanging("CategoryID");
                this._CategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryID");
                this.OnCategoryIDChanged();
            }
        }
        private int _CategoryID;
        partial void OnCategoryIDChanging(int value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Models", "FK_ProductCategories_Categories", "Categories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Category Categories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("Models.FK_ProductCategories_Categories", "Categories").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("Models.FK_ProductCategories_Categories", "Categories").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Category> CategoriesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("Models.FK_ProductCategories_Categories", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Category>("Models.FK_ProductCategories_Categories", "Categories", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Models", "FK_ProductCategories_Products", "Products")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Products
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("Models.FK_ProductCategories_Products", "Products").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("Models.FK_ProductCategories_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("Models.FK_ProductCategories_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("Models.FK_ProductCategories_Products", "Products", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Models.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Models", Name="Product")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Product : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="program">Initial value of Program.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static Product CreateProduct(int id, string productID, string productName, int status, string program, global::System.DateTime createdDate, global::System.DateTime modifiedDate)
        {
            Product product = new Product();
            product.ID = id;
            product.ProductID = productID;
            product.ProductName = productName;
            product.Status = status;
            product.Program = program;
            product.CreatedDate = createdDate;
            product.ModifiedDate = modifiedDate;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private string _ProductID;
        partial void OnProductIDChanging(string value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this.ReportPropertyChanging("ProductName");
                this._ProductName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductName");
                this.OnProductNameChanged();
            }
        }
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property SKU in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU
        {
            get
            {
                return this._SKU;
            }
            set
            {
                this.OnSKUChanging(value);
                this.ReportPropertyChanging("SKU");
                this._SKU = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SKU");
                this.OnSKUChanged();
            }
        }
        private string _SKU;
        partial void OnSKUChanging(string value);
        partial void OnSKUChanged();
        /// <summary>
        /// There are no comments for Property ProductURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductURL
        {
            get
            {
                return this._ProductURL;
            }
            set
            {
                this.OnProductURLChanging(value);
                this.ReportPropertyChanging("ProductURL");
                this._ProductURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ProductURL");
                this.OnProductURLChanged();
            }
        }
        private string _ProductURL;
        partial void OnProductURLChanging(string value);
        partial void OnProductURLChanged();
        /// <summary>
        /// There are no comments for Property ImageURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL
        {
            get
            {
                return this._ImageURL;
            }
            set
            {
                this.OnImageURLChanging(value);
                this.ReportPropertyChanging("ImageURL");
                this._ImageURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ImageURL");
                this.OnImageURLChanged();
            }
        }
        private string _ImageURL;
        partial void OnImageURLChanging(string value);
        partial void OnImageURLChanged();
        /// <summary>
        /// There are no comments for Property BuyURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyURL
        {
            get
            {
                return this._BuyURL;
            }
            set
            {
                this.OnBuyURLChanging(value);
                this.ReportPropertyChanging("BuyURL");
                this._BuyURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BuyURL");
                this.OnBuyURLChanged();
            }
        }
        private string _BuyURL;
        partial void OnBuyURLChanging(string value);
        partial void OnBuyURLChanged();
        /// <summary>
        /// There are no comments for Property ShortDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription
        {
            get
            {
                return this._ShortDescription;
            }
            set
            {
                this.OnShortDescriptionChanging(value);
                this.ReportPropertyChanging("ShortDescription");
                this._ShortDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ShortDescription");
                this.OnShortDescriptionChanged();
            }
        }
        private string _ShortDescription;
        partial void OnShortDescriptionChanging(string value);
        partial void OnShortDescriptionChanged();
        /// <summary>
        /// There are no comments for Property LongDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LongDescription
        {
            get
            {
                return this._LongDescription;
            }
            set
            {
                this.OnLongDescriptionChanging(value);
                this.ReportPropertyChanging("LongDescription");
                this._LongDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LongDescription");
                this.OnLongDescriptionChanged();
            }
        }
        private string _LongDescription;
        partial void OnLongDescriptionChanging(string value);
        partial void OnLongDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Brand in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                this.OnBrandChanging(value);
                this.ReportPropertyChanging("Brand");
                this._Brand = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Brand");
                this.OnBrandChanged();
            }
        }
        private string _Brand;
        partial void OnBrandChanging(string value);
        partial void OnBrandChanged();
        /// <summary>
        /// There are no comments for Property Keywords in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords
        {
            get
            {
                return this._Keywords;
            }
            set
            {
                this.OnKeywordsChanging(value);
                this.ReportPropertyChanging("Keywords");
                this._Keywords = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Keywords");
                this.OnKeywordsChanged();
            }
        }
        private string _Keywords;
        partial void OnKeywordsChanging(string value);
        partial void OnKeywordsChanged();
        /// <summary>
        /// There are no comments for Property PartNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this._PartNumber;
            }
            set
            {
                this.OnPartNumberChanging(value);
                this.ReportPropertyChanging("PartNumber");
                this._PartNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PartNumber");
                this.OnPartNumberChanged();
            }
        }
        private string _PartNumber;
        partial void OnPartNumberChanging(string value);
        partial void OnPartNumberChanged();
        /// <summary>
        /// There are no comments for Property ManufacturerName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerName
        {
            get
            {
                return this._ManufacturerName;
            }
            set
            {
                this.OnManufacturerNameChanging(value);
                this.ReportPropertyChanging("ManufacturerName");
                this._ManufacturerName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ManufacturerName");
                this.OnManufacturerNameChanged();
            }
        }
        private string _ManufacturerName;
        partial void OnManufacturerNameChanging(string value);
        partial void OnManufacturerNameChanged();
        /// <summary>
        /// There are no comments for Property UPC in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UPC
        {
            get
            {
                return this._UPC;
            }
            set
            {
                this.OnUPCChanging(value);
                this.ReportPropertyChanging("UPC");
                this._UPC = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UPC");
                this.OnUPCChanged();
            }
        }
        private string _UPC;
        partial void OnUPCChanging(string value);
        partial void OnUPCChanged();
        /// <summary>
        /// There are no comments for Property Classification in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Classification
        {
            get
            {
                return this._Classification;
            }
            set
            {
                this.OnClassificationChanging(value);
                this.ReportPropertyChanging("Classification");
                this._Classification = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Classification");
                this.OnClassificationChanged();
            }
        }
        private global::System.Nullable<int> _Classification;
        partial void OnClassificationChanging(global::System.Nullable<int> value);
        partial void OnClassificationChanged();
        /// <summary>
        /// There are no comments for Property Attributes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Attributes
        {
            get
            {
                return this._Attributes;
            }
            set
            {
                this.OnAttributesChanging(value);
                this.ReportPropertyChanging("Attributes");
                this._Attributes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Attributes");
                this.OnAttributesChanged();
            }
        }
        private string _Attributes;
        partial void OnAttributesChanging(string value);
        partial void OnAttributesChanged();
        /// <summary>
        /// There are no comments for Property Discount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> Discount
        {
            get
            {
                return this._Discount;
            }
            set
            {
                this.OnDiscountChanging(value);
                this.ReportPropertyChanging("Discount");
                this._Discount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Discount");
                this.OnDiscountChanged();
            }
        }
        private global::System.Nullable<decimal> _Discount;
        partial void OnDiscountChanging(global::System.Nullable<decimal> value);
        partial void OnDiscountChanged();
        /// <summary>
        /// There are no comments for Property DiscountType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountType
        {
            get
            {
                return this._DiscountType;
            }
            set
            {
                this.OnDiscountTypeChanging(value);
                this.ReportPropertyChanging("DiscountType");
                this._DiscountType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DiscountType");
                this.OnDiscountTypeChanged();
            }
        }
        private string _DiscountType;
        partial void OnDiscountTypeChanging(string value);
        partial void OnDiscountTypeChanged();
        /// <summary>
        /// There are no comments for Property SalePrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> SalePrice
        {
            get
            {
                return this._SalePrice;
            }
            set
            {
                this.OnSalePriceChanging(value);
                this.ReportPropertyChanging("SalePrice");
                this._SalePrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SalePrice");
                this.OnSalePriceChanged();
            }
        }
        private global::System.Nullable<decimal> _SalePrice;
        partial void OnSalePriceChanging(global::System.Nullable<decimal> value);
        partial void OnSalePriceChanged();
        /// <summary>
        /// There are no comments for Property RetailPrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> RetailPrice
        {
            get
            {
                return this._RetailPrice;
            }
            set
            {
                this.OnRetailPriceChanging(value);
                this.ReportPropertyChanging("RetailPrice");
                this._RetailPrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RetailPrice");
                this.OnRetailPriceChanged();
            }
        }
        private global::System.Nullable<decimal> _RetailPrice;
        partial void OnRetailPriceChanging(global::System.Nullable<decimal> value);
        partial void OnRetailPriceChanged();
        /// <summary>
        /// There are no comments for Property BeginDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> BeginDate
        {
            get
            {
                return this._BeginDate;
            }
            set
            {
                this.OnBeginDateChanging(value);
                this.ReportPropertyChanging("BeginDate");
                this._BeginDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BeginDate");
                this.OnBeginDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _BeginDate;
        partial void OnBeginDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnBeginDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this.ReportPropertyChanging("EndDate");
                this._EndDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndDate");
                this.OnEndDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property ShippingCost in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> ShippingCost
        {
            get
            {
                return this._ShippingCost;
            }
            set
            {
                this.OnShippingCostChanging(value);
                this.ReportPropertyChanging("ShippingCost");
                this._ShippingCost = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ShippingCost");
                this.OnShippingCostChanged();
            }
        }
        private global::System.Nullable<decimal> _ShippingCost;
        partial void OnShippingCostChanging(global::System.Nullable<decimal> value);
        partial void OnShippingCostChanged();
        /// <summary>
        /// There are no comments for Property ShippingInformation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingInformation
        {
            get
            {
                return this._ShippingInformation;
            }
            set
            {
                this.OnShippingInformationChanging(value);
                this.ReportPropertyChanging("ShippingInformation");
                this._ShippingInformation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ShippingInformation");
                this.OnShippingInformationChanged();
            }
        }
        private string _ShippingInformation;
        partial void OnShippingInformationChanging(string value);
        partial void OnShippingInformationChanged();
        /// <summary>
        /// There are no comments for Property ShippingAvailability in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingAvailability
        {
            get
            {
                return this._ShippingAvailability;
            }
            set
            {
                this.OnShippingAvailabilityChanging(value);
                this.ReportPropertyChanging("ShippingAvailability");
                this._ShippingAvailability = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ShippingAvailability");
                this.OnShippingAvailabilityChanged();
            }
        }
        private string _ShippingAvailability;
        partial void OnShippingAvailabilityChanging(string value);
        partial void OnShippingAvailabilityChanged();
        /// <summary>
        /// There are no comments for Property Currency in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this._Currency;
            }
            set
            {
                this.OnCurrencyChanging(value);
                this.ReportPropertyChanging("Currency");
                this._Currency = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Currency");
                this.OnCurrencyChanged();
            }
        }
        private string _Currency;
        partial void OnCurrencyChanging(string value);
        partial void OnCurrencyChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Program in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Program
        {
            get
            {
                return this._Program;
            }
            set
            {
                this.OnProgramChanging(value);
                this.ReportPropertyChanging("Program");
                this._Program = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Program");
                this.OnProgramChanged();
            }
        }
        private string _Program;
        partial void OnProgramChanging(string value);
        partial void OnProgramChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for ProductCategories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Models", "FK_ProductCategories_Products", "ProductCategories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProductCategory> ProductCategories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProductCategory>("Models.FK_ProductCategories_Products", "ProductCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProductCategory>("Models.FK_ProductCategories_Products", "ProductCategories", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Models.Store in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Models", Name="Store")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Store : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Store object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="storeName">Initial value of StoreName.</param>
        /// <param name="storeID">Initial value of StoreID.</param>
        /// <param name="program">Initial value of Program.</param>
        /// <param name="status">Initial value of Status.</param>
        public static Store CreateStore(int id, string storeName, string storeID, string program, int status)
        {
            Store store = new Store();
            store.ID = id;
            store.StoreName = storeName;
            store.StoreID = storeID;
            store.Program = program;
            store.Status = status;
            return store;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property StoreName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreName
        {
            get
            {
                return this._StoreName;
            }
            set
            {
                this.OnStoreNameChanging(value);
                this.ReportPropertyChanging("StoreName");
                this._StoreName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("StoreName");
                this.OnStoreNameChanged();
            }
        }
        private string _StoreName;
        partial void OnStoreNameChanging(string value);
        partial void OnStoreNameChanged();
        /// <summary>
        /// There are no comments for Property StoreID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreID
        {
            get
            {
                return this._StoreID;
            }
            set
            {
                this.OnStoreIDChanging(value);
                this.ReportPropertyChanging("StoreID");
                this._StoreID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("StoreID");
                this.OnStoreIDChanged();
            }
        }
        private string _StoreID;
        partial void OnStoreIDChanging(string value);
        partial void OnStoreIDChanged();
        /// <summary>
        /// There are no comments for Property StoreURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreURL
        {
            get
            {
                return this._StoreURL;
            }
            set
            {
                this.OnStoreURLChanging(value);
                this.ReportPropertyChanging("StoreURL");
                this._StoreURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StoreURL");
                this.OnStoreURLChanged();
            }
        }
        private string _StoreURL;
        partial void OnStoreURLChanging(string value);
        partial void OnStoreURLChanged();
        /// <summary>
        /// There are no comments for Property ImageURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL
        {
            get
            {
                return this._ImageURL;
            }
            set
            {
                this.OnImageURLChanging(value);
                this.ReportPropertyChanging("ImageURL");
                this._ImageURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ImageURL");
                this.OnImageURLChanged();
            }
        }
        private string _ImageURL;
        partial void OnImageURLChanging(string value);
        partial void OnImageURLChanged();
        /// <summary>
        /// There are no comments for Property Program in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Program
        {
            get
            {
                return this._Program;
            }
            set
            {
                this.OnProgramChanging(value);
                this.ReportPropertyChanging("Program");
                this._Program = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Program");
                this.OnProgramChanged();
            }
        }
        private string _Program;
        partial void OnProgramChanging(string value);
        partial void OnProgramChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
    }
}
